version: '3.0'
services:
  db:
    image: postgres
    container_name: chatDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chatApp
      - POSTGRES_USER=chatApp
      - POSTGRES_PASSWORD=chatApp
