spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/chatApp
    username: chatApp
    password: chatApp
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    root: INFO
    com:
      zaxxer:
        hikari: DEBUG
server:
  error:
    include-message: always
socket-server:
  port: 8085
  host: localhost


